steps:
- name: docker-build
  dockerBuild:
    user: iceci
    imageName: utils
    dockerSecret: dockerhub
    contextPath: utils
    dockerfilePath: utils/Dockerfile
    tags:
    - "3"
    - latest
